config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'

  resources :courses do
    member do
      get :select
      get :selectd
      get :quit
      get :open
      get :close
      get :advselect
			get :submit
			get :gotosubmit
			get :deletefromsubmit
    	get :advselect
		end
    collection do
      get :list
			get :submit
    	get :schedule
		end
  end

  resources :grades, only: [:index, :update]
  resources :users do
    collection do
      get :list
      get :listc
    end
  end

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController

  before_action :teacher_logged_in, only: [:update]

  def update
    @grade=Grade.find_by_id(params[:id])
    if @grade.update_attributes!(:grade => params[:grade][:grade])
      flash={:success => "#{@grade.user.name} #{@grade.course.name}的成绩已成功修改为 #{@grade.grade}"}
    else
      flash={:danger => "上传失败.请重试"}
    end
    redirect_to grades_path(course_id: params[:course_id]), flash: flash
  end

  def index
    if teacher_logged_in?
      @course=Course.find_by_id(params[:course_id])
      @grades=@course.grades
    elsif student_logged_in?
      @grades=current_user.grades
    else
      redirect_to root_path, flash: {:warning=>"请先登陆"}
    end
  end


  private

  # Confirms a teacher logged-in user.
  def teacher_logged_in
    unless teacher_logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

end

app/views/grades/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <%= render "shared/sidenav" %>

    </div>
    <div class="col-sm-10">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <% if teacher_logged_in? %><h3 class="panel-title">成绩管理: <%=@course.name%></h3><% end %>
          <% if student_logged_in? %><h3 class="panel-title">成绩列表</h3><% end %>
        </div>
        <div class="panel-body" style="min-height: 450px">
          <table class="table table-striped table-hover">
            <thead>

            <tr>
              <th>学号</th>
              <th>名字</th>
              <th>专业</th>
              <th>培养单位</th>
              <th>课程</th>
              <th>目前分数</th>

            </tr>
            </thead>
            <tbody>

            <% @grades.each do |grade| %>
                <tr>
                  <td><%= grade.user.num %></td>
                  <td><%= grade.user.name %></td>
                  <td><%= grade.user.major %></td>
                  <td><%= grade.user.department %></td>
                  <td><%= grade.course.name %></td>
                  <td><%= grade.grade %></td>

                  <% if teacher_logged_in? %>
                      <%= form_for grade, url: grade_url(id: grade.id, course_id: grade.course.id), method: :patch do |f| %>
                          <td><%= f.text_field :grade %></td>
                          <td><%= f.submit "提交", class: "btn btn-success btn-xs" %></td>
                      <% end %>
                  <% end %>

                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>