config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'

  resources :courses do
    member do
      get :select
      get :selectd
      get :quit
      get :open
      get :close
      get :advselect
			get :submit
			get :gotosubmit
			get :deletefromsubmit
    	get :advselect
		end
    collection do
      get :list
			get :submit
    	get :schedule
		end
  end

  resources :grades, only: [:index, :update]
  resources :users do
    collection do
      get :list
      get :listc
    end
  end

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_sidenav.html.erb
<div class="panel-group" id="accordion">

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">

        <% if teacher_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#CourseCollapse"><span class="glyphicon glyphicon-user"></span>
              课程管理</a>
        <% end %>

        <% if student_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#CourseCollapse"><span class="glyphicon glyphicon-user"></span>
              选修课程</a>
        <% end %>

      </h4>
    </div>

    <div id="CourseCollapse" class="panel-collapse collapse <%= "in" if ["courses"].include?(params[:controller]) %>">
      <ul class="list-group">

        <% if teacher_logged_in? %>
            <li class="list-group-item">
              <%= link_to courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 已授课程
                  <span class="label label-info pull-right"><%= current_user.teaching_courses.length %></span>
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to new_course_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 创建新课程
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to list_courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 建议课程
                  <span class="label label-info pull-right"><%= (Course.where(:open => true)-current_user.courses).length %></span>
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to listc_users_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 已建议课程
                 
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to new_user_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 添加学生
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to list_users_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 已选学生
                  <span class="label label-info pull-right"><%= current_user.students.length %></span>
              <% end %>
            </li>
        <% end %>

        <% if student_logged_in? %>
            <li class="list-group-item">
              <%= link_to list_courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 选修课程
                  <span class="label label-info pull-right"><%= (Course.where(:open => true)-current_user.courses).length-current_user.unsubmit_num %></span>
              <% end %>
            </li>
	   
           <li class="list-group-item">
              <%= link_to submit_courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 待提交课程
                  <span class="label label-info pull-right"><%= current_user.unsubmit_num %></span>
              <% end %>
            </li>

            <li class="list-group-item">
              <%= link_to courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 已选课程
                  <span class="label label-info pull-right"><%= current_user.courses.length %></span>
              <% end %>
            </li>

            <li class="list-group-item">
              <%= link_to schedule_courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 查看课表
		  <span class="label label-info pull-right"><%= current_user.courses.length %></span>	
              <% end %>
            </li>

        <% end %>

      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <% if teacher_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#GradeCollapse"><span class="glyphicon glyphicon-user"></span>
              成绩管理</a>
        <% end %>

        <% if student_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#GradeCollapse"><span class="glyphicon glyphicon-user"></span>
              所有成绩</a>
        <% end %>
      </h4>
    </div>

    <div id="GradeCollapse" class="panel-collapse collapse <%= "in" if ["grades"].include?(params[:controller]) %>">
      <div class="list-group">

        <% if teacher_logged_in? %>
            <% current_user.teaching_courses.each do |course| %>
                <li class="list-group-item">
                  <%= link_to grades_path(course_id: course.id), :method => :get do %>
                      <span class="glyphicon glyphicon-chevron-right"></span> <%= course.name %>
                      <span class="label label-info pull-right"><%= course.users.length %></span>
                  <% end %>
                </li>
            <% end %>

        <% end %>

        <% if student_logged_in? %>
            <li class="list-group-item">
              <%= link_to grades_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 所有成绩
              <% end %>
            </li>
        <% end %>

      </div>
    </div>
  </div>
</div>